apiVersion: frankframework.org/v1
kind: Frank
metadata:
  name: frank-docker-example
  namespace: frank-docker-example
spec:
  containerImage: nexus.frankframework.org/frankframework
  imageVersion: 8.2.0-SNAPSHOT
  replicas: 1
  resourcesMap:
    frank-docker-example: -L https://github.com/jjansenvr/Frank-docker-example/raw/main/builds/Frank-docker-example_2024-05-31_15-50-13.jar
  envVarsMap:
    instance.name: frank-docker-example
    dtap.stage: LOC
    dtap.side: local
  labelsMap:
    example-label: label
  podManager: Deployment